import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {initializeCatalog,createCatalog} from './catalog.mjs';
import {recognitionClasses} from './recognition-classes.mjs';
const fail=(status,message)=>{throw Object.assign(Error(message),{status});};
function setup(){
 const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE dishes(id INTEGER PRIMARY KEY,restaurant_id INTEGER,name TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,archived_at TEXT); CREATE TABLE samples(id INTEGER PRIMARY KEY,dish_id INTEGER,created_at TEXT);');initializeCatalog(db);
 const access={tenantId:u=>u.id,demand:(u,cap)=>{if(!u?.caps?.includes(cap))fail(403,'Denied');},restaurant:(id,u)=>{if(Number(id)!==u.restaurant)fail(404,'Not found');return{id:Number(id)};},dish:(id,u)=>{const d=db.prepare('SELECT * FROM dishes WHERE id=?').get(Number(id));if(!d||d.restaurant_id!==u.restaurant)fail(404,'Not found');return d;},audit:()=>{}};
 const catalog=createCatalog({db,access,fail,text:s=>s.trim(),media:{describeSample:(s,owner)=>{assert.equal(owner,1);assert.equal(s.data,undefined);return {url:`/api/samples/${s.id}`,image_key:null,media_status:'legacy'};}}});
 const manager={id:1,restaurant:1,caps:['catalog.read','catalog.write']};
 const call=async(p,method='GET',body={},user=manager)=>{let result;await catalog.route({p,method,body,user,url:new URL('http://test'+p+'?restaurantId=1'),res:{},json:(_,status,payload)=>{result={status,...payload};}});return result;};
 return {db,call,manager};
}
test('canonical labels/IDs match installed COCO80 and have Arabic names',()=>{const require=createRequire(import.meta.url);const {CLASSES}=require('@tensorflow-models/coco-ssd/dist/classes.js');assert.equal(recognitionClasses.length,80);assert.deepEqual(recognitionClasses.map(c=>[c.id,c.label]),Object.values(CLASSES).map(c=>[c.id,c.displayName]));assert.ok(recognitionClasses.every(c=>c.labelAr));});
test('legacy dish defaults and variants survive additive initialization',async()=>{const {db,call}=setup();db.prepare('INSERT INTO dishes(restaurant_id,name) VALUES(1,?)').run('Meal');initializeCatalog(db);const d=(await call('/api/dishes')).dishes[0];assert.equal(d.kind,'dish');assert.equal(d.recognitionMode,'reference');assert.deepEqual(d.detectorClasses,[]);db.close();});
test('object/person detector configuration, duplicate warnings and partial updates',async()=>{const {db,call}=setup();const first=await call('/api/dishes','POST',{restaurantId:1,name:'Staff',kind:'person',recognitionMode:'detector',detectorClasses:['person']});assert.equal(first.dish.kind,'person');const second=await call('/api/dishes','POST',{restaurantId:1,name:'Visitor',kind:'person',recognitionMode:'detector',detectorClasses:['person']});assert.equal(second.warnings[0].code,'ambiguous-detector-mapping');const update=await call(`/api/dishes/${first.dish.id}`,'POST',{name:'Employee'});assert.equal(update.dish.name,'Employee');assert.deepEqual(update.dish.detectorClasses,['person']);const object=await call('/api/dishes','POST',{restaurantId:1,name:'Bottle',kind:'object',recognitionMode:'detector',detectorClasses:['bottle']});assert.equal(object.dish.kind,'object');db.close();});
test('roles and restaurant scopes apply to generic catalog',async()=>{const {db,call,manager}=setup();const d=(await call('/api/dishes','POST',{restaurantId:1,name:'Person',kind:'person',recognitionMode:'detector',detectorClasses:['person']})).dish;await assert.rejects(call('/api/dishes','POST',{restaurantId:1,name:'Object'},{...manager,caps:['catalog.read']}),{status:403});await assert.rejects(call(`/api/dishes/${d.id}`,'POST',{name:'Attack'},{...manager,restaurant:2}),{status:404});await assert.rejects(call('/api/recognition/classes','GET',{},null),{status:403});db.close();});
test('rejects invalid classes, scalar JSON and unauthorized mass assignment',async()=>{const {db,call}=setup();for(const fields of [{detectorClasses:['plate']},{detectorClasses:'person'},{recognitionMode:'detector',detectorClasses:[]},{recognitionMode:'bad'},{kind:'all'},{owner_id:99},{name:42}])await assert.rejects(call('/api/dishes','POST',{restaurantId:1,name:'Test',...fields}),{status:400});const d=(await call('/api/dishes','POST',{restaurantId:1,name:'Test'})).dish;await assert.rejects(call(`/api/dishes/${d.id}`,'POST',{restaurantId:2}),{status:400});db.prepare('UPDATE dishes SET detector_classes=? WHERE id=?').run('"person"',d.id);await assert.rejects(call('/api/dishes'),{status:500});db.close();});
test('reference matching permits optional canonical detector constraints',async()=>{const {db,call}=setup();const result=await call('/api/dishes','POST',{restaurantId:1,name:'Custom drink',kind:'drink',recognitionMode:'reference',detectorClasses:['cup','bottle']});assert.deepEqual(result.dish.detectorClasses,['cup','bottle']);db.close();});

test('public classes use canonical name and Arabic label; variants omit media BLOB',async()=>{const {db,call}=setup();const result=await call('/api/recognition/classes');assert.deepEqual(result.classes[0],{id:1,name:'person',label:'شخص'});const d=(await call('/api/dishes','POST',{restaurantId:1,name:'Meal'})).dish;db.prepare('INSERT INTO samples(dish_id,variant_label) VALUES(?,?)').run(d.id,'Small');const samples=(await call('/api/dishes')).dishes[0].samples;assert.equal(samples[0].variantLabel,'Small');assert.equal(samples[0].media_status,'legacy');assert.equal(samples[0].url,'/api/samples/1');db.close();});
