import {objectBody,isoTime,identityPart,pageQuery} from './validation.mjs';
import {ensureCrossing} from './event-identity.mjs';
import {parseImage} from './media-store.mjs';
import {cairoDayInterval,cairoDate} from './business-day.mjs';
const TEMPLATES=[
 ['power','انقطاع الكهرباء والتصوير',3,5,'UPS للكاميرات وNVR والمعالجة والشبكة؛ اختبار التشغيل والاستعادة.'],
 ['frozen','تجمد مصدر الفيديو',3,5,'متابعة وصول إطارات جديدة؛ إيقاف الادعاء بالتغطية عند توقف المصدر.'],
 ['occlusion','تداخل الأطباق والصواني والأيدي',4,4,'زاوية تصوير ثابتة واختبار أربعة عناصر؛ مراجعة العبورات المجهولة.'],
 ['classification','تشابه أصناف الأطباق والمشروبات',4,4,'بيانات اختبار مستقلة؛ الأصناف المتطابقة تحتاج ربط طلب أو علامة ظاهرة.'],
 ['pos_semantics','إلغاء ومرتجعات ومجاني وهالك وتوقيت الطلب',4,4,'فصل الإلغاء قبل الخروج عن بعده؛ توثيق أكواد الأصناف ومراجعة اليوم.'],
 ['storage','امتلاء التخزين وفقد طابور الإرسال',3,5,'حصص تخزين ومراقبة المساحة ونسخ احتياطي؛ لا تحذف دليلًا دون سياسة.'],
 ['access','تعديل البيانات أو تجاوز الصلاحيات',3,5,'صلاحيات حسب الدور والمطعم، مفاتيح محدودة، وسجل تدقيق واعتماد مدير.'],
 ['model_drift','تغير النموذج أو القائمة أو ظروف التصوير',3,4,'حفظ بصمة النموذج والإعدادات والفيديو؛ إعادة اختبار عند التغيير.'],
 ['accusation','اعتبار الفارق العددي دليل سرقة',3,5,'الفارق حالة تحتاج مراجعة، وليس دليل إدانة؛ راجع التغطية والكاشير.']
];
export function initializeGovernance(db){db.exec(`
 CREATE TABLE IF NOT EXISTS risks(id INTEGER PRIMARY KEY,owner_id INTEGER,restaurant_id INTEGER,code TEXT,title TEXT,probability INTEGER,impact INTEGER,mitigation TEXT,status TEXT DEFAULT 'open',assignee TEXT DEFAULT '',notes TEXT DEFAULT '',updated_at TEXT,UNIQUE(owner_id,restaurant_id,code));
 CREATE TABLE IF NOT EXISTS day_reviews(id INTEGER PRIMARY KEY,owner_id INTEGER,restaurant_id INTEGER,business_date TEXT,status TEXT,pos_revision TEXT,actor_id INTEGER,reason TEXT,acknowledged_incomplete INTEGER,updated_at TEXT,UNIQUE(owner_id,restaurant_id,business_date));
 CREATE TABLE IF NOT EXISTS event_corrections(id INTEGER PRIMARY KEY,event_id INTEGER,owner_id INTEGER,actor_id INTEGER,action TEXT,new_dish_id INTEGER,reason TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS corrections_event_idx ON event_corrections(event_id,id);
 CREATE TABLE IF NOT EXISTS unknown_crossings(id INTEGER PRIMARY KEY,owner_id INTEGER,restaurant_id INTEGER,session_id TEXT,track_id TEXT,crossing_id TEXT,occurred_at TEXT,experiment_id INTEGER,media_time_sec REAL,reason TEXT,snapshot_mime TEXT,snapshot BLOB,resolved_at TEXT,resolution TEXT,resolved_by INTEGER,resolved_dish_id INTEGER,UNIQUE(owner_id,session_id,track_id,crossing_id));
 CREATE INDEX IF NOT EXISTS unknown_restaurant_idx ON unknown_crossings(restaurant_id,experiment_id,occurred_at);
 CREATE VIEW IF NOT EXISTS effective_events AS SELECT e.*,COALESCE(c.new_dish_id,e.dish_id) effective_dish_id,CASE WHEN c.action='void' THEN 1 ELSE 0 END effective_void,c.id correction_id FROM events e LEFT JOIN event_corrections c ON c.id=(SELECT MAX(c2.id) FROM event_corrections c2 WHERE c2.event_id=e.id);`);}
export function createGovernance({db,access,fail,text,media,sources}){
 const seed=(rid,user)=>{for(const[code,title,p,i,mitigation]of TEMPLATES)db.prepare('INSERT OR IGNORE INTO risks(owner_id,restaurant_id,code,title,probability,impact,mitigation,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(access.tenantId(user),rid,code,title,p,i,mitigation,new Date().toISOString());};
 const changed=(rid,at)=>db.prepare("UPDATE day_reviews SET status='needs_review',updated_at=? WHERE restaurant_id=? AND business_date=? AND status='approved'").run(new Date().toISOString(),rid,cairoDate(at));
 async function route({p,method,url,body,user,res,json}){
  if(p==='/api/risks'){const r=access.restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user);access.demand(user,method==='GET'?'risks.read':'risks.write',r.id);seed(r.id,user);if(method==='GET'){const risks=db.prepare('SELECT * FROM risks WHERE owner_id=? AND restaurant_id=? ORDER BY probability*impact DESC,id').all(access.tenantId(user),r.id).map(x=>({...x,score:x.probability*x.impact,priority:x.probability*x.impact>=15?'high':x.probability*x.impact>=8?'medium':'low'}));json(res,200,{risks,note:'Initial scores are planning assumptions, not measured probabilities. Acceptance requires authorized review.'});return true;}}
  let m=p.match(/^\/api\/risks\/(\d+)$/);if(m&&method==='POST'){const risk=db.prepare('SELECT * FROM risks WHERE id=? AND owner_id=?').get(Number(m[1]),access.tenantId(user));if(!risk)fail(404,'Risk not found');access.restaurant(risk.restaurant_id,user);access.demand(user,'risks.write',risk.restaurant_id);const probability=body.probability??risk.probability,impact=body.impact??risk.impact,status=body.status??risk.status;if(![probability,impact].every(n=>Number.isInteger(n)&&n>=1&&n<=5)||!['open','mitigating','accepted','closed'].includes(status))fail(400,'Invalid risk assessment');if(['accepted','closed'].includes(status))access.demand(user,'day.approve',risk.restaurant_id);const mitigation=body.mitigation===undefined?risk.mitigation:text(body.mitigation,2000),notes=body.notes===undefined?risk.notes:String(body.notes).trim().slice(0,2000),assignee=body.assignee===undefined?risk.assignee:String(body.assignee).trim().slice(0,120);if(['accepted','closed'].includes(status)&&(!notes||!assignee))fail(400,'Responsible person and review evidence required to accept or close risk');db.prepare('UPDATE risks SET probability=?,impact=?,status=?,mitigation=?,assignee=?,notes=?,updated_at=? WHERE id=?').run(probability,impact,status,mitigation,assignee,notes,new Date().toISOString(),risk.id);access.audit(user,'risk.updated',risk.id,{restaurantId:risk.restaurant_id,probability,impact,status});json(res,200,{ok:true});return true;}
  if(p==='/api/day-reviews'){const r=access.restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user);const day=method==='GET'?url.searchParams.get('businessDate'):body.businessDate;cairoDayInterval(day);access.demand(user,method==='GET'?'pos.read':'day.approve',r.id);if(method==='GET'){json(res,200,{review:db.prepare('SELECT * FROM day_reviews WHERE owner_id=? AND restaurant_id=? AND business_date=?').get(access.tenantId(user),r.id,day)||null});return true;}if(method==='POST'){const status=body.action==='reopen'?'open':body.action==='approve'?'approved':null;if(!status)fail(400,'Choose approve or reopen');const reason=text(body.reason,2000),latest=db.prepare('SELECT revision FROM pos_revisions WHERE user_id=? AND restaurant_id=? AND business_date=? ORDER BY id DESC LIMIT 1').get(access.tenantId(user),r.id,day);if(status==='approved'&&(!latest||latest.revision!==body.posRevision))fail(409,'POS revision changed or missing');if(status==='approved'&&body.acknowledgeIncomplete!==true)fail(400,'Explicit acknowledgement of incomplete/unverified coverage is required');db.prepare('INSERT INTO day_reviews(owner_id,restaurant_id,business_date,status,pos_revision,actor_id,reason,acknowledged_incomplete,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_id,restaurant_id,business_date) DO UPDATE SET status=excluded.status,pos_revision=excluded.pos_revision,actor_id=excluded.actor_id,reason=excluded.reason,acknowledged_incomplete=excluded.acknowledged_incomplete,updated_at=excluded.updated_at').run(access.tenantId(user),r.id,day,status,latest?.revision||null,user.id,reason,Number(body.acknowledgeIncomplete===true),new Date().toISOString());access.audit(user,'day.'+status,day,{restaurantId:r.id,posRevision:latest?.revision,reason});json(res,200,{ok:true,status,note:'Manager review is not proof of accurate recognition or absence of losses.'});return true;}}
  m=p.match(/^\/api\/events\/(\d+)\/corrections$/);if(m){const event=db.prepare('SELECT * FROM events WHERE id=? AND user_id=?').get(Number(m[1]),access.tenantId(user));if(!event)fail(404,'Event not found');access.restaurant(event.restaurant_id,user);access.demand(user,method==='GET'?'reports.read':'day.approve',event.restaurant_id);if(method==='GET'){json(res,200,{corrections:db.prepare('SELECT id,actor_id,action,new_dish_id,reason,created_at FROM event_corrections WHERE event_id=? ORDER BY id').all(event.id)});return true;}if(method==='POST'){if(!['void','reclassify'].includes(body.action))fail(400,'Invalid correction');let id=null;if(body.action==='reclassify'){const d=access.dish(body.dishId,user);if(d.restaurant_id!==event.restaurant_id)fail(400,'Dish belongs elsewhere');if(d.archived_at&&event.occurred_at>=d.archived_at)fail(409,'Dish was archived at the event time');id=d.id;}const reason=text(body.reason,2000);db.exec('BEGIN');try{db.prepare('INSERT INTO event_corrections(event_id,owner_id,actor_id,action,new_dish_id,reason,dish_name_snapshot) VALUES(?,?,?,?,?,?,?)').run(event.id,access.tenantId(user),user.id,body.action,id,reason,id?access.dish(id,user).name:null);if(!event.experiment_id)changed(event.restaurant_id,event.occurred_at);access.audit(user,'event.corrected',event.id,{restaurantId:event.restaurant_id,action:body.action,dishId:id,reason});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}json(res,201,{ok:true});return true;}}
  if(p==='/api/unknown-events'){
   const r=access.restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user),owner=access.tenantId(user);access.demand(user,method==='GET'?'reports.read':'events.write',r.id);
   if(method==='GET'){
    const exp=url.searchParams.get('experimentId');if(exp){const e=db.prepare('SELECT restaurant_id FROM experiments WHERE id=? AND user_id=?').get(Number(exp),owner);if(!e||e.restaurant_id!==r.id)fail(404,'Experiment not found');}
    const {limit,beforeId}=pageQuery(url,{defaultLimit:100}),day=url.searchParams.get('businessDate'),fromDay=day||url.searchParams.get('fromDate'),toDay=day||url.searchParams.get('toDate');if((fromDay&&!toDay)||(!fromDay&&toDay)||fromDay>toDay)fail(400,'Invalid date range');const from=fromDay?cairoDayInterval(fromDay).from:'0001',to=toDay?cairoDayInterval(toDay).to:'9999',state=url.searchParams.get('state');if(state!==null&&!['unresolved','resolved','all'].includes(state))fail(400,'Invalid review state');
    const records=db.prepare("SELECT id,COALESCE(original_session_id,session_id) session_id,track_id,crossing_id,occurred_at,experiment_id,media_time_sec,reason,resolved_at,resolution,resolved_dish_id,confirmed_event_id,source_id,image_key,media_status,(image_key IS NOT NULL OR snapshot IS NOT NULL) has_snapshot FROM unknown_crossings WHERE owner_id=? AND restaurant_id=? AND experiment_id IS ? AND occurred_at>=? AND occurred_at<? AND (? IS NULL OR id<?) AND (? IS NULL OR ?='all' OR (?='unresolved' AND resolved_at IS NULL) OR (?='resolved' AND resolved_at IS NOT NULL)) ORDER BY id DESC LIMIT ?").all(owner,r.id,exp?Number(exp):null,from,to,beforeId,beforeId,state,state,state,state,limit+1),hasMore=records.length>limit;if(hasMore)records.pop();for(const x of records){x.media_status=x.media_status==='legacy'?'legacy':x.image_key?media.status(x.image_key,owner):'none';x.snapshot_url=x.has_snapshot?'/api/unknown-events/'+x.id+'/snapshot':null;}json(res,200,{records,hasMore,nextBeforeId:hasMore?records.at(-1).id:null});return true;
   }
   if(method==='POST'){
    if(!Array.isArray(body.events)||body.events.length>100)fail(400,'Provide up to100 unknown events');const events=body.events.map(value=>{const e=objectBody(value,'unknown event'),at=isoTime(e.occurredAt);let experimentId=null,mediaTime=null;if(e.experimentId!==undefined&&e.experimentId!==null){const x=db.prepare('SELECT * FROM experiments WHERE id=? AND user_id=?').get(Number(e.experimentId),owner);if(!x||x.restaurant_id!==r.id)fail(404,'Experiment not found');if(typeof e.mediaTimeSec!=='number'||!Number.isFinite(e.mediaTimeSec)||e.mediaTimeSec<0||e.mediaTimeSec>x.duration_sec+1)fail(400,'Invalid media time');experimentId=x.id;mediaTime=e.mediaTimeSec;}else if(e.mediaTimeSec!==undefined)fail(400,'Media time requires experiment');const source=sources?.registered(e.sourceId,r.id,user),sourceLeaseId=sources?.eventLease(source,e.sourceLeaseId,at,experimentId)||null;return{session:identityPart(e.sessionId,'session',text),track:identityPart(e.trackId,'track',text),crossing:identityPart(e.crossingId,'crossing',text),at,experimentId,mediaTime,sourceId:source?.source_id||null,sourceLeaseId,reason:text(e.reason??'uncertain',200),image:parseImage(e.image,512*1024)};});
    let inserted=0,mediaPending=0;media.begin();db.exec('BEGIN');try{for(const e of events){
     const identity=ensureCrossing(db,e,{owner,restaurantId:r.id,kind:'unknown',fail}),previous=identity.unknown_id?db.prepare('SELECT * FROM unknown_crossings WHERE id=?').get(identity.unknown_id):null,known=identity.event_id?db.prepare('SELECT * FROM events WHERE id=?').get(identity.event_id):null;
     const inherited=previous||known,expected=inherited?.image_key||(inherited?.snapshot?media.keyFor(owner,{data:Buffer.from(inherited.snapshot)}):null),stored=e.image?media.put(owner,e.image,expected):{key:inherited?.image_key||null,status:inherited?.media_status||'none'};
     if(previous){if(e.image)db.prepare("UPDATE unknown_crossings SET image_key=?,media_status=?,snapshot_mime=?,snapshot=CASE WHEN ?='ready' THEN NULL ELSE snapshot END WHERE id=?").run(stored.key,stored.status,e.image.mime,stored.status,previous.id);}
     else{const id=Number(db.prepare('INSERT INTO unknown_crossings(owner_id,restaurant_id,session_id,original_session_id,track_id,crossing_id,occurred_at,experiment_id,media_time_sec,reason,snapshot_mime,snapshot,image_key,media_status,identity_key,source_id,resolved_at,resolution,resolved_by,resolved_dish_id,confirmed_event_id,source_lease_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(owner,r.id,identity.storageSession,e.session,e.track,e.crossing,e.at,e.experimentId,e.mediaTime,e.reason,e.image?.mime||known?.snapshot_mime||null,e.image?null:known?.snapshot||null,stored.key,stored.status,identity.identity_key,e.sourceId,known?new Date().toISOString():null,known?'confirm':null,known?user.id:null,known?.dish_id||null,known?.id||null,e.sourceLeaseId).lastInsertRowid);db.prepare('UPDATE crossing_identities SET unknown_id=? WHERE identity_key=?').run(id,identity.identity_key);inserted++;if(!e.experimentId&&!known)changed(r.id,e.at);}
     if(known&&stored.key&&!known.image_key&&!known.snapshot)db.prepare('UPDATE events SET image_key=?,media_status=?,snapshot_mime=? WHERE id=?').run(stored.key,stored.status,e.image?.mime||null,known.id);
     if(stored.key&&media.status(stored.key,owner)!=='ready'&&!inherited?.snapshot)mediaPending++;
    }if(inserted)access.audit(user,'unknown.received',r.id,{restaurantId:r.id,inserted});db.exec('COMMIT');media.commit();}catch(e){db.exec('ROLLBACK');media.rollback();throw e;}json(res,200,{inserted,duplicates:events.length-inserted,...(mediaPending?{mediaPending}:{})});return true;
   }
  }
  m=p.match(/^\/api\/unknown-events\/(\d+)\/(resolve|snapshot)$/);if(m){
   const owner=access.tenantId(user),row=db.prepare('SELECT * FROM unknown_crossings WHERE id=? AND owner_id=?').get(Number(m[1]),owner);if(!row)fail(404,'Record not found');access.restaurant(row.restaurant_id,user);
   if(m[2]==='snapshot'&&method==='GET'){access.demand(user,'reports.read',row.restaurant_id);let image;if(row.snapshot)image={mime:row.snapshot_mime,data:Buffer.from(row.snapshot)};else if(row.image_key)image=media.read(row.image_key,owner);else fail(404,'No snapshot');res.writeHead(200,{'Content-Type':image.mime,'Cache-Control':'private, no-store'});res.end(image.data);return true;}
   if(m[2]==='resolve'&&method==='POST'){
    access.demand(user,'day.approve',row.restaurant_id);if(!['exclude','confirm'].includes(body.action))fail(400,'Invalid resolution');const reason=text(body.reason,2000);let dish=null;if(body.action==='confirm'){dish=access.dish(body.dishId,user);if(dish.restaurant_id!==row.restaurant_id)fail(400,'Wrong dish');if(dish.archived_at&&row.occurred_at>=dish.archived_at)fail(409,'Dish was archived at the crossing time');}
    if(row.resolved_at){if(row.resolution!==body.action||row.resolved_dish_id!==(dish?.id||null))fail(409,'Already resolved differently');json(res,200,{ok:true,duplicate:true,eventId:row.confirmed_event_id||null});return true;}
    db.exec('BEGIN');try{const identity=db.prepare('SELECT * FROM crossing_identities WHERE identity_key=?').get(row.identity_key);let eventId=identity?.event_id||null;const known=eventId?db.prepare('SELECT * FROM events WHERE id=?').get(eventId):null;if(known&&(body.action==='exclude'||known.dish_id!==dish?.id))fail(409,'Crossing is already counted; use the event correction workflow');
     if(dish&&!known){eventId=Number(db.prepare('INSERT INTO events(user_id,restaurant_id,dish_id,session_id,original_session_id,track_id,crossing_id,camera,occurred_at,confidence,mode,snapshot_mime,snapshot,experiment_id,media_time_sec,image_key,media_status,identity_key,dish_name_snapshot,source_id,source_lease_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(owner,row.restaurant_id,dish.id,'iep:v2:'+row.identity_key,row.original_session_id||row.session_id,row.track_id,row.crossing_id,'Reviewed unknown',row.occurred_at,0,'manual',row.snapshot_mime,row.snapshot,row.experiment_id,row.media_time_sec,row.image_key,row.media_status,row.identity_key,dish.name,row.source_id,row.source_lease_id).lastInsertRowid);db.prepare('UPDATE crossing_identities SET event_id=? WHERE identity_key=?').run(eventId,row.identity_key);}
     db.prepare('UPDATE unknown_crossings SET resolved_at=?,resolution=?,resolved_by=?,resolved_dish_id=?,confirmed_event_id=? WHERE id=?').run(new Date().toISOString(),body.action,user.id,dish?.id||null,eventId,row.id);if(!row.experiment_id)changed(row.restaurant_id,row.occurred_at);access.audit(user,'unknown.resolved',row.id,{restaurantId:row.restaurant_id,action:body.action,dishId:dish?.id,eventId,reason});db.exec('COMMIT');json(res,200,{ok:true,eventId});
    }catch(e){db.exec('ROLLBACK');throw e;}return true;
   }
  }
  return false;
 }
 return{route,changed};
}
