import {cairoDayInterval,cairoDate} from './business-day.mjs';
const TEMPLATES=[
 ['power','انقطاع الكهرباء والتصوير',3,5,'UPS للكاميرات وNVR والمعالجة والشبكة؛ اختبار التشغيل والاستعادة.'],
 ['frozen','تجمد مصدر الفيديو',3,5,'متابعة وصول إطارات جديدة؛ إيقاف الادعاء بالتغطية عند توقف المصدر.'],
 ['occlusion','تداخل الأطباق والصواني والأيدي',4,4,'زاوية تصوير ثابتة واختبار أربعة عناصر؛ مراجعة العبورات المجهولة.'],
 ['classification','تشابه أصناف الأطباق والمشروبات',4,4,'بيانات اختبار مستقلة؛ الأصناف المتطابقة تحتاج ربط طلب أو علامة ظاهرة.'],
 ['pos_semantics','إلغاء ومرتجعات ومجاني وهالك وتوقيت الطلب',4,4,'فصل الإلغاء قبل الخروج عن بعده؛ توثيق أكواد الأصناف ومراجعة اليوم.'],
 ['storage','امتلاء التخزين وفقد طابور الإرسال',3,5,'حصص تخزين ومراقبة المساحة ونسخ احتياطي؛ لا تحذف دليلًا دون سياسة.'],
 ['access','تعديل البيانات أو تجاوز الصلاحيات',3,5,'صلاحيات حسب الدور والمطعم، مفاتيح محدودة، وسجل تدقيق واعتماد مدير.'],
 ['model_drift','تغير النموذج أو القائمة أو ظروف التصوير',3,4,'حفظ بصمة النموذج والإعدادات والفيديو؛ إعادة اختبار عند التغيير.'],
 ['accusation','اعتبار الفارق العددي دليل سرقة',3,5,'الفارق حالة تحتاج مراجعة، وليس دليل إدانة؛ راجع التغطية والكاشير.']
];
export function initializeGovernance(db){db.exec(`
 CREATE TABLE IF NOT EXISTS risks(id INTEGER PRIMARY KEY,owner_id INTEGER,restaurant_id INTEGER,code TEXT,title TEXT,probability INTEGER,impact INTEGER,mitigation TEXT,status TEXT DEFAULT 'open',assignee TEXT DEFAULT '',notes TEXT DEFAULT '',updated_at TEXT,UNIQUE(owner_id,restaurant_id,code));
 CREATE TABLE IF NOT EXISTS day_reviews(id INTEGER PRIMARY KEY,owner_id INTEGER,restaurant_id INTEGER,business_date TEXT,status TEXT,pos_revision TEXT,actor_id INTEGER,reason TEXT,acknowledged_incomplete INTEGER,updated_at TEXT,UNIQUE(owner_id,restaurant_id,business_date));
 CREATE TABLE IF NOT EXISTS event_corrections(id INTEGER PRIMARY KEY,event_id INTEGER,owner_id INTEGER,actor_id INTEGER,action TEXT,new_dish_id INTEGER,reason TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS corrections_event_idx ON event_corrections(event_id,id);
 CREATE TABLE IF NOT EXISTS unknown_crossings(id INTEGER PRIMARY KEY,owner_id INTEGER,restaurant_id INTEGER,session_id TEXT,track_id TEXT,crossing_id TEXT,occurred_at TEXT,experiment_id INTEGER,media_time_sec REAL,reason TEXT,snapshot_mime TEXT,snapshot BLOB,resolved_at TEXT,resolution TEXT,resolved_by INTEGER,resolved_dish_id INTEGER,UNIQUE(owner_id,session_id,track_id,crossing_id));
 CREATE INDEX IF NOT EXISTS unknown_restaurant_idx ON unknown_crossings(restaurant_id,experiment_id,occurred_at);
 CREATE VIEW IF NOT EXISTS effective_events AS SELECT e.*,COALESCE(c.new_dish_id,e.dish_id) effective_dish_id,CASE WHEN c.action='void' THEN 1 ELSE 0 END effective_void,c.id correction_id FROM events e LEFT JOIN event_corrections c ON c.id=(SELECT MAX(c2.id) FROM event_corrections c2 WHERE c2.event_id=e.id);`);}
export function createGovernance({db,access,fail,text}){
 const seed=(rid,user)=>{for(const[code,title,p,i,mitigation]of TEMPLATES)db.prepare('INSERT OR IGNORE INTO risks(owner_id,restaurant_id,code,title,probability,impact,mitigation,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(access.tenantId(user),rid,code,title,p,i,mitigation,new Date().toISOString());};
 const image=value=>{if(!value)return{mime:null,data:null};const m=/^data:(image\/(?:jpeg|png));base64,([A-Za-z0-9+/]+={0,2})$/.exec(value);if(!m)fail(400,'Invalid snapshot');const data=Buffer.from(m[2],'base64');if(data.length>512*1024)fail(413,'Snapshot too large');const valid=m[1]==='image/png'?data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):data[0]===255&&data[1]===216&&data[2]===255;if(!valid)fail(400,'Invalid snapshot signature');return{mime:m[1],data};};
 const changed=(rid,at)=>db.prepare("UPDATE day_reviews SET status='needs_review',updated_at=? WHERE restaurant_id=? AND business_date=? AND status='approved'").run(new Date().toISOString(),rid,cairoDate(at));
 async function route({p,method,url,body,user,res,json}){
  if(p==='/api/risks'){const r=access.restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user);access.demand(user,method==='GET'?'risks.read':'risks.write',r.id);seed(r.id,user);if(method==='GET'){const risks=db.prepare('SELECT * FROM risks WHERE owner_id=? AND restaurant_id=? ORDER BY probability*impact DESC,id').all(access.tenantId(user),r.id).map(x=>({...x,score:x.probability*x.impact,priority:x.probability*x.impact>=15?'high':x.probability*x.impact>=8?'medium':'low'}));json(res,200,{risks,note:'Initial scores are planning assumptions, not measured probabilities. Acceptance requires authorized review.'});return true;}}
  let m=p.match(/^\/api\/risks\/(\d+)$/);if(m&&method==='POST'){const risk=db.prepare('SELECT * FROM risks WHERE id=? AND owner_id=?').get(Number(m[1]),access.tenantId(user));if(!risk)fail(404,'Risk not found');access.restaurant(risk.restaurant_id,user);access.demand(user,'risks.write',risk.restaurant_id);const probability=body.probability??risk.probability,impact=body.impact??risk.impact,status=body.status??risk.status;if(![probability,impact].every(n=>Number.isInteger(n)&&n>=1&&n<=5)||!['open','mitigating','accepted','closed'].includes(status))fail(400,'Invalid risk assessment');if(['accepted','closed'].includes(status))access.demand(user,'day.approve',risk.restaurant_id);const mitigation=body.mitigation===undefined?risk.mitigation:text(body.mitigation,2000),notes=body.notes===undefined?risk.notes:String(body.notes).trim().slice(0,2000),assignee=body.assignee===undefined?risk.assignee:String(body.assignee).trim().slice(0,120);if(['accepted','closed'].includes(status)&&(!notes||!assignee))fail(400,'Responsible person and review evidence required to accept or close risk');db.prepare('UPDATE risks SET probability=?,impact=?,status=?,mitigation=?,assignee=?,notes=?,updated_at=? WHERE id=?').run(probability,impact,status,mitigation,assignee,notes,new Date().toISOString(),risk.id);access.audit(user,'risk.updated',risk.id,{restaurantId:risk.restaurant_id,probability,impact,status});json(res,200,{ok:true});return true;}
  if(p==='/api/day-reviews'){const r=access.restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user);const day=method==='GET'?url.searchParams.get('businessDate'):body.businessDate;cairoDayInterval(day);access.demand(user,method==='GET'?'pos.read':'day.approve',r.id);if(method==='GET'){json(res,200,{review:db.prepare('SELECT * FROM day_reviews WHERE owner_id=? AND restaurant_id=? AND business_date=?').get(access.tenantId(user),r.id,day)||null});return true;}if(method==='POST'){const status=body.action==='reopen'?'open':body.action==='approve'?'approved':null;if(!status)fail(400,'Choose approve or reopen');const reason=text(body.reason,2000),latest=db.prepare('SELECT revision FROM pos_revisions WHERE user_id=? AND restaurant_id=? AND business_date=? ORDER BY id DESC LIMIT 1').get(access.tenantId(user),r.id,day);if(status==='approved'&&(!latest||latest.revision!==body.posRevision))fail(409,'POS revision changed or missing');if(status==='approved'&&body.acknowledgeIncomplete!==true)fail(400,'Explicit acknowledgement of incomplete/unverified coverage is required');db.prepare('INSERT INTO day_reviews(owner_id,restaurant_id,business_date,status,pos_revision,actor_id,reason,acknowledged_incomplete,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(owner_id,restaurant_id,business_date) DO UPDATE SET status=excluded.status,pos_revision=excluded.pos_revision,actor_id=excluded.actor_id,reason=excluded.reason,acknowledged_incomplete=excluded.acknowledged_incomplete,updated_at=excluded.updated_at').run(access.tenantId(user),r.id,day,status,latest?.revision||null,user.id,reason,Number(body.acknowledgeIncomplete===true),new Date().toISOString());access.audit(user,'day.'+status,day,{restaurantId:r.id,posRevision:latest?.revision,reason});json(res,200,{ok:true,status,note:'Manager review is not proof of accurate recognition or absence of losses.'});return true;}}
  m=p.match(/^\/api\/events\/(\d+)\/corrections$/);if(m){const event=db.prepare('SELECT * FROM events WHERE id=? AND user_id=?').get(Number(m[1]),access.tenantId(user));if(!event)fail(404,'Event not found');access.restaurant(event.restaurant_id,user);access.demand(user,method==='GET'?'reports.read':'day.approve',event.restaurant_id);if(method==='GET'){json(res,200,{corrections:db.prepare('SELECT id,actor_id,action,new_dish_id,reason,created_at FROM event_corrections WHERE event_id=? ORDER BY id').all(event.id)});return true;}if(method==='POST'){if(!['void','reclassify'].includes(body.action))fail(400,'Invalid correction');let id=null;if(body.action==='reclassify'){const d=access.dish(body.dishId,user);if(d.restaurant_id!==event.restaurant_id)fail(400,'Dish belongs elsewhere');id=d.id;}const reason=text(body.reason,2000);db.exec('BEGIN');try{db.prepare('INSERT INTO event_corrections(event_id,owner_id,actor_id,action,new_dish_id,reason) VALUES(?,?,?,?,?,?)').run(event.id,access.tenantId(user),user.id,body.action,id,reason);if(!event.experiment_id)changed(event.restaurant_id,event.occurred_at);access.audit(user,'event.corrected',event.id,{restaurantId:event.restaurant_id,action:body.action,dishId:id,reason});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}json(res,201,{ok:true});return true;}}
  if(p==='/api/unknown-events'){const r=access.restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user);access.demand(user,method==='GET'?'reports.read':'events.write',r.id);if(method==='GET'){const exp=url.searchParams.get('experimentId');if(exp){const e=db.prepare('SELECT restaurant_id FROM experiments WHERE id=? AND user_id=?').get(Number(exp),access.tenantId(user));if(!e||e.restaurant_id!==r.id)fail(404,'Experiment not found');}const records=db.prepare('SELECT id,session_id,track_id,occurred_at,experiment_id,media_time_sec,reason,resolved_at,resolution,resolved_dish_id,snapshot IS NOT NULL has_snapshot FROM unknown_crossings WHERE owner_id=? AND restaurant_id=? AND experiment_id IS ? ORDER BY id DESC LIMIT 200').all(access.tenantId(user),r.id,exp?Number(exp):null).map(x=>({...x,snapshot_url:x.has_snapshot?'/api/unknown-events/'+x.id+'/snapshot':null}));json(res,200,{records});return true;}if(method==='POST'){if(!Array.isArray(body.events)||body.events.length>100)fail(400,'Provide up to100 unknown events');let inserted=0;db.exec('BEGIN');try{for(const e of body.events){const at=new Date(e.occurredAt);if(!Number.isFinite(at.getTime()))fail(400,'Invalid event time');let exp=null,time=null;if(e.experimentId){const x=db.prepare('SELECT * FROM experiments WHERE id=? AND user_id=?').get(Number(e.experimentId),access.tenantId(user));if(!x||x.restaurant_id!==r.id)fail(404,'Experiment not found');if(typeof e.mediaTimeSec!=='number'||!Number.isFinite(e.mediaTimeSec)||e.mediaTimeSec<0||e.mediaTimeSec>x.duration_sec)fail(400,'Invalid media time');exp=x.id;time=e.mediaTimeSec;}const snap=image(e.image);const count=Number(db.prepare('INSERT OR IGNORE INTO unknown_crossings(owner_id,restaurant_id,session_id,track_id,crossing_id,occurred_at,experiment_id,media_time_sec,reason,snapshot_mime,snapshot) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(access.tenantId(user),r.id,(exp?'experiment:'+exp+':':'')+text(e.sessionId),text(String(e.trackId??'')),text(String(e.crossingId??'')),at.toISOString(),exp,time,text(e.reason||'uncertain',200),snap.mime,snap.data).changes);inserted+=count;if(count&&!exp)changed(r.id,at.toISOString());}if(inserted)access.audit(user,'unknown.received',r.id,{restaurantId:r.id,inserted});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}json(res,200,{inserted,duplicates:body.events.length-inserted});return true;}}
  m=p.match(/^\/api\/unknown-events\/(\d+)\/(resolve|snapshot)$/);if(m){const row=db.prepare('SELECT * FROM unknown_crossings WHERE id=? AND owner_id=?').get(Number(m[1]),access.tenantId(user));if(!row)fail(404,'Record not found');access.restaurant(row.restaurant_id,user);if(m[2]==='snapshot'&&method==='GET'){access.demand(user,'reports.read',row.restaurant_id);if(!row.snapshot)fail(404,'No snapshot');res.writeHead(200,{'Content-Type':row.snapshot_mime,'Cache-Control':'private, no-store'});res.end(Buffer.from(row.snapshot));return true;}if(m[2]==='resolve'&&method==='POST'){access.demand(user,'day.approve',row.restaurant_id);if(!['exclude','confirm'].includes(body.action))fail(400,'Invalid resolution');const reason=text(body.reason,2000);let dish=null;if(body.action==='confirm'){dish=access.dish(body.dishId,user);if(dish.restaurant_id!==row.restaurant_id)fail(400,'Wrong dish');}if(row.resolved_at){if(row.resolution!==body.action||row.resolved_dish_id!==(dish?.id||null))fail(409,'Already resolved differently');json(res,200,{ok:true,duplicate:true});return true;}db.exec('BEGIN');try{if(dish)db.prepare('INSERT OR IGNORE INTO events(user_id,restaurant_id,dish_id,session_id,track_id,crossing_id,camera,occurred_at,confidence,mode,snapshot_mime,snapshot,experiment_id,media_time_sec) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(access.tenantId(user),row.restaurant_id,dish.id,'unknown:'+row.id,'review','review','Reviewed unknown',row.occurred_at,0,'manual',row.snapshot_mime,row.snapshot,row.experiment_id,row.media_time_sec);db.prepare('UPDATE unknown_crossings SET resolved_at=?,resolution=?,resolved_by=?,resolved_dish_id=? WHERE id=?').run(new Date().toISOString(),body.action,user.id,dish?.id||null,row.id);if(!row.experiment_id)changed(row.restaurant_id,row.occurred_at);access.audit(user,'unknown.resolved',row.id,{restaurantId:row.restaurant_id,action:body.action,dishId:dish?.id,reason});db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}json(res,200,{ok:true});return true;}}
  return false;
 }
 return{route,changed};
}
