import {initializeOperations,operations} from './operations.mjs';
import http from 'node:http';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {mkdirSync,readFileSync,existsSync,statSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const hash=(value)=>createHash('sha256').update(value).digest('hex');
const passwordHash=(value,salt)=>scryptSync(value,salt,64).toString('hex');
export function createApp({dataDir=process.env.IEP_DATA_DIR||path.join(root,'.local/data'),adminPassword=process.env.IEP_ADMIN_PASSWORD,adminEmail=process.env.IEP_ADMIN_EMAIL||'admin@iep.local'}={}) {
 if(!adminPassword||adminPassword.length<12) throw new Error('Set IEP_ADMIN_PASSWORD to a password of at least 12 characters.');
 mkdirSync(dataDir,{recursive:true});
 const db=new DatabaseSync(path.join(dataDir,'iep.sqlite')); db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;
 CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,name TEXT,salt TEXT,password TEXT);
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id INTEGER REFERENCES users(id),expires INTEGER);
 CREATE TABLE IF NOT EXISTS restaurants(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),name TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS dishes(id INTEGER PRIMARY KEY,restaurant_id INTEGER REFERENCES restaurants(id) ON DELETE CASCADE,name TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS samples(id INTEGER PRIMARY KEY,dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,mime TEXT,data BLOB,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),restaurant_id INTEGER REFERENCES restaurants(id),dish_id INTEGER REFERENCES dishes(id),session_id TEXT,track_id TEXT,crossing_id TEXT,camera TEXT,occurred_at TEXT,confidence REAL,mode TEXT DEFAULT 'automatic',snapshot_mime TEXT,snapshot BLOB,UNIQUE(user_id,session_id,track_id,crossing_id));`);
 if(!db.prepare('PRAGMA table_info(events)').all().some(c=>c.name==='mode'))db.exec("ALTER TABLE events ADD COLUMN mode TEXT DEFAULT 'automatic'");
 for(const c of ['snapshot_mime TEXT','snapshot BLOB'])if(!db.prepare('PRAGMA table_info(events)').all().some(x=>x.name===c.split(' ')[0]))db.exec('ALTER TABLE events ADD COLUMN '+c);
 initializeOperations(db);
 if(!db.prepare('SELECT id FROM users WHERE email=?').get(adminEmail)){const salt=randomBytes(16).toString('hex');db.prepare('INSERT INTO users(email,name,salt,password) VALUES(?,?,?,?)').run(adminEmail,'IEP Administrator',salt,passwordHash(adminPassword,salt));}
 const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
 const text=(v,max=120)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,'Invalid text field');return v.trim();};
 const restaurant=(id,user)=>{const r=db.prepare('SELECT * FROM restaurants WHERE id=? AND user_id=?').get(Number(id),user.id);if(!r)fail(404,'Restaurant not found');return r;};
 const dish=(id,user)=>{const d=db.prepare('SELECT d.* FROM dishes d JOIN restaurants r ON r.id=d.restaurant_id WHERE d.id=? AND r.user_id=?').get(Number(id),user.id);if(!d)fail(404,'Dish not found');return d;};
 const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
 const ops=operations({db,fail,text,restaurant,dish});
 const server=http.createServer(async(req,res)=>{try{
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('Permissions-Policy','camera=(self), microphone=()');
 const url=new URL(req.url,'http://localhost');const p=url.pathname;const method=req.method;
 if(!['GET','HEAD'].includes(method)&&req.headers.origin){const origin=new URL(req.headers.origin);if(origin.host!==req.headers.host)fail(403,'Cross-origin request blocked');}
 let body={};if(!['GET','HEAD'].includes(method)){let bytes=0,chunks=[];for await(const chunk of req){bytes+=chunk.length;if(bytes>3*1024*1024)fail(413,'Request too large');chunks.push(chunk);}if(bytes){try{body=JSON.parse(Buffer.concat(chunks));}catch{fail(400,'Invalid JSON');}}}
 if(p==='/api/health')return json(res,200,{ok:true});
 if(p==='/api/login'&&method==='POST'){
 const ip=req.socket.remoteAddress;const now=Date.now();const hits=loginAttempts.get(ip)||[];const recent=hits.filter(t=>now-t<60000);if(recent.length>=10)fail(429,'Try again in a minute');recent.push(now);loginAttempts.set(ip,recent);
 const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(body.email||''));if(!u||typeof body.password!=='string'||body.password.length>1024||!timingSafeEqual(Buffer.from(u.password,'hex'),Buffer.from(passwordHash(body.password,u.salt),'hex')))fail(401,'Invalid email or password');
 const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash(token),u.id,Date.now()+86400000*7);res.setHeader('Set-Cookie',`iep_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800${req.socket.encrypted||['1','true'].includes(process.env.IEP_SECURE_COOKIE)?'; Secure':''}`);return json(res,200,{user:{id:u.id,email:u.email,name:u.name}});
 }
 const token= /(?:^|;\s*)iep_session=([a-f0-9]{64})(?:;|$)/.exec(req.headers.cookie||'')?.[1];const user=token&&db.prepare('SELECT u.id,u.email,u.name FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?').get(hash(token),Date.now());
 if(p.startsWith('/api/')&&!user)fail(401,'Login required');
 if(await ops.route({p,method,url,body,user,res,json}))return;
 if(p==='/api/me')return json(res,200,{user});
 if(p==='/api/logout'&&method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(hash(token));res.setHeader('Set-Cookie','iep_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0');return json(res,200,{ok:true});}
 if(p==='/api/restaurants'){
 if(method==='GET')return json(res,200,{restaurants:db.prepare('SELECT id,name,created_at FROM restaurants WHERE user_id=? ORDER BY id').all(user.id)});
 if(method==='POST'){const id=db.prepare('INSERT INTO restaurants(user_id,name) VALUES(?,?)').run(user.id,text(body.name)).lastInsertRowid;return json(res,201,{restaurant:restaurant(id,user)});}
 }
 if(p==='/api/dishes'){
 const r=restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user);
 if(method==='GET'){const dishes=db.prepare('SELECT * FROM dishes WHERE restaurant_id=? ORDER BY id').all(r.id).map(d=>({...d,samples:db.prepare('SELECT id,created_at FROM samples WHERE dish_id=?').all(d.id).map(s=>({...s,url:`/api/samples/${s.id}`}))}));return json(res,200,{dishes});}
 if(method==='POST'){const id=db.prepare('INSERT INTO dishes(restaurant_id,name) VALUES(?,?)').run(r.id,text(body.name)).lastInsertRowid;return json(res,201,{dish:dish(id,user)});}
 }
 let match=p.match(/^\/api\/dishes\/(\d+)(\/samples)?$/);if(match){const d=dish(match[1],user);
 if(match[2]&&method==='POST'){const m=/^data:(image\/(?:jpeg|png));base64,([A-Za-z0-9+/]+={0,2})$/.exec(body.image||'');if(!m)fail(400,'Use a JPEG or PNG image');const data=Buffer.from(m[2],'base64');if(data.length>2*1024*1024)fail(413,'Image exceeds 2 MiB');const valid=m[1]==='image/png'?data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):data[0]===255&&data[1]===216&&data[2]===255;if(!valid)fail(400,'Invalid image signature');const id=db.prepare('INSERT INTO samples(dish_id,mime,data) VALUES(?,?,?)').run(d.id,m[1],data).lastInsertRowid;return json(res,201,{sample:{id,url:`/api/samples/${id}`,created_at:new Date().toISOString()}});}
 if(!match[2]&&method==='DELETE'){if(db.prepare('SELECT id FROM events WHERE dish_id=? LIMIT 1').get(d.id))fail(409,'Dish has count history and cannot be deleted');db.prepare('DELETE FROM dishes WHERE id=?').run(d.id);return json(res,200,{ok:true});}}
 match=p.match(/^\/api\/samples\/(\d+)$/);if(match){const s=db.prepare('SELECT s.* FROM samples s JOIN dishes d ON d.id=s.dish_id JOIN restaurants r ON r.id=d.restaurant_id WHERE s.id=? AND r.user_id=?').get(Number(match[1]),user.id);if(!s)fail(404,'Sample not found');if(method==='DELETE'){db.prepare('DELETE FROM samples WHERE id=?').run(s.id);return json(res,200,{ok:true});}if(method==='GET'){res.writeHead(200,{'Content-Type':s.mime,'Cache-Control':'private, max-age=60'});return res.end(Buffer.from(s.data));}}
 match=p.match(/^\/api\/events\/(\d+)\/snapshot$/);if(match&&method==='GET'){const e=db.prepare('SELECT snapshot_mime,snapshot FROM events WHERE id=? AND user_id=?').get(Number(match[1]),user.id);if(!e?.snapshot)fail(404,'Snapshot not found');res.writeHead(200,{'Content-Type':e.snapshot_mime,'Cache-Control':'private, max-age=60'});return res.end(Buffer.from(e.snapshot));}
 if(p==='/api/events'&&method==='POST'){const r=restaurant(body.restaurantId,user);if(!Array.isArray(body.events)||body.events.length>200)fail(400,'Provide up to 200 events');const events=body.events.map(e=>{const d=dish(e.dishId,user);if(d.restaurant_id!==r.id)fail(400,'Dish does not belong to restaurant');const date=new Date(e.occurredAt);if(!Number.isFinite(date.getTime()))fail(400,'Invalid event time');if(typeof e.confidence!=='number'||e.confidence<0||e.confidence>1)fail(400,'Invalid confidence');if(e.mode&&!['manual','automatic'].includes(e.mode))fail(400,'Invalid event mode');let experimentId=null,mediaTime=null;if(e.experimentId){const experiment=ops.experiment(e.experimentId,user,r.id);experimentId=experiment.id;if(typeof e.mediaTimeSec!=='number'||!Number.isFinite(e.mediaTimeSec)||e.mediaTimeSec<0||e.mediaTimeSec>experiment.duration_sec+1)fail(400,'Invalid media time');mediaTime=e.mediaTimeSec;}else if(e.mediaTimeSec!==undefined)fail(400,'Media time requires experiment');let snapshot=null,mime=null;if(e.image){const m=/^data:(image\/(?:jpeg|png));base64,([A-Za-z0-9+/]+={0,2})$/.exec(e.image);if(!m)fail(400,'Invalid snapshot');snapshot=Buffer.from(m[2],'base64');mime=m[1];if(snapshot.length>512*1024)fail(413,'Snapshot exceeds 512 KiB');const valid=mime==='image/png'?snapshot.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):snapshot[0]===255&&snapshot[1]===216&&snapshot[2]===255;if(!valid)fail(400,'Invalid snapshot signature');}return [user.id,r.id,d.id,(experimentId?'experiment:'+experimentId+':':'')+text(e.sessionId),text(String(e.trackId??'')),text(String(e.crossingId??'')),text(e.camera||'Mobile'),date.toISOString(),e.confidence,e.mode||'automatic',mime,snapshot,experimentId,mediaTime];});let inserted=0;db.exec('BEGIN');try{for(const e of events)inserted+=Number(db.prepare('INSERT OR IGNORE INTO events(user_id,restaurant_id,dish_id,session_id,track_id,crossing_id,camera,occurred_at,confidence,mode,snapshot_mime,snapshot,experiment_id,media_time_sec) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(...e).changes);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return json(res,200,{inserted,duplicates:events.length-inserted});}
 if((p==='/api/reports'||p==='/api/reports.csv')&&method==='GET'){const r=restaurant(url.searchParams.get('restaurantId'),user);const from=url.searchParams.get('from')||'1970-01-01T00:00:00.000Z';const to=url.searchParams.get('to')||'9999-12-31T23:59:59.999Z';if(!Number.isFinite(Date.parse(from))||!Number.isFinite(Date.parse(to)))fail(400,'Invalid date range');const experimentId=url.searchParams.get('experimentId');if(experimentId)ops.experiment(experimentId,user,r.id);const args=[experimentId?Number(experimentId):null,r.id,new Date(from).toISOString(),new Date(to).toISOString()];const totals=db.prepare('SELECT d.id dishId,d.name dishName,COUNT(*) count FROM events e JOIN dishes d ON d.id=e.dish_id WHERE e.experiment_id IS ? AND e.restaurant_id=? AND e.occurred_at>=? AND e.occurred_at<=? GROUP BY d.id ORDER BY count DESC').all(...args);const events=db.prepare('SELECT e.id,e.dish_id,d.name dish_name,e.camera,e.occurred_at,e.confidence,e.mode,e.experiment_id,e.media_time_sec,CASE WHEN e.snapshot IS NOT NULL THEN \'/api/events/\'||e.id||\'/snapshot\' ELSE NULL END snapshot_url FROM events e JOIN dishes d ON d.id=e.dish_id WHERE e.experiment_id IS ? AND e.restaurant_id=? AND e.occurred_at>=? AND e.occurred_at<=? ORDER BY e.occurred_at DESC LIMIT 1000').all(...args);if(p.endsWith('.csv')){const cell=v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';res.writeHead(200,{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="iep-counts.csv"'});return res.end('\ufeff'+['Dish,Count',...totals.map(t=>[t.dishName,t.count].map(cell).join(','))].join('\r\n'));}return json(res,200,{totals,events,total:totals.reduce((s,t)=>s+t.count,0)});}
 if(p.startsWith('/api/'))fail(404,'API route not found');
 if(method!=='GET'&&method!=='HEAD')fail(405,'Method not allowed');if(p.startsWith('/models/')){const modelDir=path.resolve(process.env.IEP_MODELS_DIR||path.join(root,'.local/models'));const relative=decodeURIComponent(p.slice('/models/'.length));if(!/^(mobilenet|detector)\/(model\.json|group\d+-shard\d+of\d+(?:\.bin)?)$/.test(relative))fail(404,'Model asset not found');const f=path.resolve(modelDir,relative);if(!f.startsWith(modelDir+path.sep)||!existsSync(f)||!statSync(f).isFile())fail(404,'Model asset unavailable');res.writeHead(200,{'Content-Type':f.endsWith('.json')?'application/json':'application/octet-stream','Cache-Control':'public, max-age=86400'});return res.end(readFileSync(f));}const vendors={'/vendor/tf.min.js':'@tensorflow/tfjs/dist/tf.min.js','/vendor/mobilenet.min.js':'@tensorflow-models/mobilenet/dist/mobilenet.min.js','/vendor/coco-ssd.min.js':'@tensorflow-models/coco-ssd/dist/coco-ssd.min.js'};if(vendors[p]){const f=path.join(root,'node_modules',vendors[p]);if(!existsSync(f))fail(404,'Vendor asset unavailable');res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'public, max-age=86400'});return res.end(readFileSync(f));}const publicDir=path.join(root,'public');const filename=path.resolve(publicDir,'.'+decodeURIComponent(p==='/'?'/index.html':p));if(!filename.startsWith(publicDir+path.sep)||!existsSync(filename)||!statSync(filename).isFile())fail(404,'Not found');const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png'};res.writeHead(200,{'Content-Type':types[path.extname(filename)]||'application/octet-stream','Cache-Control':'no-cache'});res.end(method==='HEAD'?undefined:readFileSync(filename));
 }catch(e){json(res,e.status||500,{error:e.status?e.message:'Internal server error'});if(!e.status)console.error(e);}});
 const loginAttempts=new Map();server.on('close',()=>db.close());return {server,db};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const {server}=createApp();server.listen(Number(process.env.PORT||3000),process.env.HOST||'127.0.0.1',()=>console.log(`IEP running on ${process.env.HOST||'127.0.0.1'}:${process.env.PORT||3000}`));}
