import {cairoDate,cairoDayInterval} from './business-day.mjs';
export {cairoDate,cairoDayInterval} from './business-day.mjs';
import {createHash} from 'node:crypto';
export function initializeOperations(db){db.exec(`
CREATE TABLE IF NOT EXISTS experiments(id INTEGER PRIMARY KEY,user_id INTEGER,restaurant_id INTEGER,name TEXT,video_name TEXT,duration_sec REAL,status TEXT DEFAULT 'created',summary TEXT DEFAULT '{}',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pos_revisions(id INTEGER PRIMARY KEY,user_id INTEGER,restaurant_id INTEGER,business_date TEXT,revision TEXT,payload TEXT,payload_hash TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,restaurant_id,business_date,revision));
CREATE TABLE IF NOT EXISTS monitors(id INTEGER PRIMARY KEY,user_id INTEGER,restaurant_id INTEGER,session_id TEXT,camera TEXT,started_at TEXT,last_heartbeat TEXT,ended_at TEXT,end_reason TEXT,UNIQUE(user_id,session_id));
CREATE TABLE IF NOT EXISTS monitor_gaps(id INTEGER PRIMARY KEY,monitor_id INTEGER,start_at TEXT,end_at TEXT,cause TEXT DEFAULT 'unknown');`);
if(!db.prepare('PRAGMA table_info(monitors)').all().some(c=>c.name==='source_id'))db.exec('ALTER TABLE monitors ADD COLUMN source_id TEXT');
if(!db.prepare('PRAGMA table_info(monitors)').all().some(c=>c.name==='stalled_at'))db.exec('ALTER TABLE monitors ADD COLUMN stalled_at TEXT');
for(const c of ['experiment_id INTEGER','media_time_sec REAL'])if(!db.prepare('PRAGMA table_info(events)').all().some(x=>x.name===c.split(' ')[0]))db.exec('ALTER TABLE events ADD COLUMN '+c);
db.exec('CREATE INDEX IF NOT EXISTS events_report_idx ON events(restaurant_id,experiment_id,occurred_at); CREATE INDEX IF NOT EXISTS monitor_restaurant_idx ON monitors(restaurant_id,user_id); CREATE INDEX IF NOT EXISTS monitor_source_idx ON monitors(user_id,restaurant_id,source_id,ended_at); CREATE INDEX IF NOT EXISTS monitor_gap_idx ON monitor_gaps(monitor_id); CREATE INDEX IF NOT EXISTS pos_day_idx ON pos_revisions(restaurant_id,user_id,business_date,id);');
}
export function operations({db,fail,text,restaurant,dish,audit=()=>{}}){
 const experiment=(id,user,rid)=>{const e=db.prepare('SELECT * FROM experiments WHERE id=? AND user_id=?').get(Number(id),(user.owner_id||user.id));if(!e||(rid&&e.restaurant_id!==rid))fail(404,'Experiment not found');restaurant(e.restaurant_id,user);return {...e,summary:JSON.parse(e.summary)};};
 const monitor=(id,user)=>{const m=db.prepare('SELECT * FROM monitors WHERE id=? AND user_id=?').get(Number(id),(user.owner_id||user.id));if(!m)fail(404,'Monitoring session not found');restaurant(m.restaurant_id,user);return m;};
 const monitoring=(rid,user,now=new Date().toISOString())=>db.prepare('SELECT * FROM monitors WHERE restaurant_id=? AND user_id=? ORDER BY id DESC LIMIT 1000').all(rid,(user.owner_id||user.id)).map(m=>{const gaps=db.prepare('SELECT start_at,end_at,cause FROM monitor_gaps WHERE monitor_id=?').all(m.id);const stale=!m.ended_at&&Date.parse(now)-Date.parse(m.last_heartbeat)>45000;if(m.stalled_at&&!m.ended_at)gaps.push({start_at:m.stalled_at,end_at:now,cause:'video_stalled',ongoing:true});else if(stale)gaps.push({start_at:new Date(Date.parse(m.last_heartbeat)+45000).toISOString(),end_at:now,cause:'unknown',ongoing:true});return {...m,status:m.ended_at?'ended':m.stalled_at?'stalled':stale?'stale':'active',gaps};});
 const date=v=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)fail(400,'Invalid business date');return v;};
 return {experiment,async route({p,method,url,body,user,res,json}){
 if(p==='/api/experiments'){const r=restaurant(method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,user);if(method==='GET'){return json(res,200,{experiments:db.prepare('SELECT id FROM experiments WHERE restaurant_id=? AND user_id=? ORDER BY id DESC').all(r.id,(user.owner_id||user.id)).map(e=>experiment(e.id,user))}),true;}if(method==='POST'){if(typeof body.durationSec!=='number'||!Number.isFinite(body.durationSec)||body.durationSec<0||body.durationSec>86400)fail(400,'Invalid video duration');const id=db.prepare('INSERT INTO experiments(user_id,restaurant_id,name,video_name,duration_sec) VALUES(?,?,?,?,?)').run((user.owner_id||user.id),r.id,text(body.name),text(body.videoName,255),body.durationSec).lastInsertRowid;audit(user,'experiment.created',Number(id),{restaurantId:r.id});return json(res,201,{experiment:experiment(id,user)}),true;}}
 let match=p.match(/^\/api\/experiments\/(\d+)$/);if(match){const e=experiment(match[1],user);if(method==='GET')return json(res,200,{experiment:e}),true;if(method==='POST'){if(!['running','completed','failed'].includes(body.status))fail(400,'Invalid experiment status');const summary=JSON.stringify(body.summary||{});if(summary.length>10000)fail(400,'Summary too large');db.prepare('UPDATE experiments SET status=?,summary=? WHERE id=?').run(body.status,summary,e.id);return json(res,200,{experiment:experiment(e.id,user)}),true;}}
 if(p==='/api/pos'&&method==='GET'){const r=restaurant(url.searchParams.get('restaurantId'),user),day=date(url.searchParams.get('businessDate'));const revisions=db.prepare('SELECT id,revision,payload,created_at FROM pos_revisions WHERE user_id=? AND restaurant_id=? AND business_date=? ORDER BY id DESC').all((user.owner_id||user.id),r.id,day).map((row,index)=>({id:row.id,revision:row.revision,created_at:row.created_at,active:index===0,items:JSON.parse(row.payload)}));return json(res,200,{businessDate:day,timeZone:'Africa/Cairo',revisions}),true;}
 if(p==='/api/pos'&&method==='POST'){const r=restaurant(body.restaurantId,user);const day=date(body.businessDate);const closed=db.prepare("SELECT status FROM day_reviews WHERE owner_id=? AND restaurant_id=? AND business_date=?").get((user.owner_id||user.id),r.id,day);if(closed?.status==='approved')fail(409,'Day is approved; authorized manager must reopen it before POS edits');const revision=text(body.revision);if(!Array.isArray(body.items)||body.items.length>500)fail(400,'Provide up to 500 POS rows');const seen=new Set();const items=body.items.map(i=>{const d=dish(i.dishId,user);if(d.restaurant_id!==r.id||seen.has(d.id))fail(400,'Invalid or duplicate POS dish');seen.add(d.id);if(d.archived_at&&!db.prepare("SELECT 1 FROM pos_revisions p,json_each(p.payload) j WHERE p.user_id=? AND p.restaurant_id=? AND p.business_date=? AND json_extract(j.value,'$.dishId')=? LIMIT 1").get((user.owner_id||user.id),r.id,day,d.id))fail(400,'Archived dish has no POS history for this day');const row={dishId:d.id,dishName:d.name};for(const k of ['sold','cancelled','complimentary','waste']){const n=i[k]??0;if(!Number.isSafeInteger(n)||n<0||n>1000000)fail(400,'Invalid POS quantity');row[k]=n;}if(row.cancelled>row.sold)fail(400,'Cancelled exceeds sold');row.expectedOut=row.sold-row.cancelled+row.complimentary+row.waste;return row;}).sort((a,b)=>a.dishId-b.dishId);const payload=JSON.stringify(items),hash=createHash('sha256').update(JSON.stringify(items.map(({dishName,...row})=>row))).digest('hex');const previous=db.prepare('SELECT * FROM pos_revisions WHERE user_id=? AND restaurant_id=? AND business_date=? AND revision=?').get((user.owner_id||user.id),r.id,day,revision);if(previous&&previous.payload_hash!==hash)fail(409,'Revision already exists with different data; use a new revision');const latest=db.prepare('SELECT id FROM pos_revisions WHERE user_id=? AND restaurant_id=? AND business_date=? ORDER BY id DESC LIMIT 1').get((user.owner_id||user.id),r.id,day);if(previous)return json(res,200,{revision:previous.revision,duplicate:true,active:latest?.id===previous.id}),true;const id=db.prepare('INSERT INTO pos_revisions(user_id,restaurant_id,business_date,revision,payload,payload_hash) VALUES(?,?,?,?,?,?)').run((user.owner_id||user.id),r.id,day,revision,payload,hash).lastInsertRowid;audit(user,'pos.revised',r.id,{restaurantId:r.id,businessDate:day,revision,revisionId:Number(id)});return json(res,201,{revision,id,duplicate:false,active:true}),true;}
 if(p==='/api/reconciliation'&&method==='GET'){const r=restaurant(url.searchParams.get('restaurantId'),user);const day=date(url.searchParams.get('businessDate'));const revision=db.prepare('SELECT * FROM pos_revisions WHERE user_id=? AND restaurant_id=? AND business_date=? ORDER BY id DESC LIMIT 1').get((user.owner_id||user.id),r.id,day);const pos=new Map((revision?JSON.parse(revision.payload):[]).map(i=>[i.dishId,i]));const interval=cairoDayInterval(day);const counts=new Map(db.prepare("SELECT effective_dish_id dish_id,SUM(CASE WHEN mode='automatic' THEN 1 ELSE 0 END) automatic,SUM(CASE WHEN mode='manual' THEN 1 ELSE 0 END) manual FROM effective_events WHERE effective_void=0 AND restaurant_id=? AND user_id=? AND experiment_id IS NULL AND occurred_at>=? AND occurred_at<? GROUP BY effective_dish_id").all(r.id,(user.owner_id||user.id),interval.from,interval.to).map(e=>[e.dish_id,e]));const rows=db.prepare('SELECT id,name,archived_at FROM dishes WHERE restaurant_id=? ORDER BY id').all(r.id).filter(d=>!d.archived_at||pos.has(d.id)||counts.has(d.id)).map(d=>{const automatic=counts.get(d.id)?.automatic||0,manual=counts.get(d.id)?.manual||0;const expected=pos.get(d.id)?.expectedOut??null;return {dishId:d.id,dishName:pos.get(d.id)?.dishName||d.name,archived:!!d.archived_at,automatic,manual,observed:automatic+manual,expectedOut:expected,difference:expected===null?null:automatic+manual-expected,pos:pos.get(d.id)||null};});const sessions=monitoring(r.id,user);const relevant=sessions.filter(m=>cairoDate(m.started_at)<=day&&cairoDate(m.ended_at||new Date())>=day);const gaps=relevant.flatMap(m=>m.gaps.filter(g=>cairoDate(g.start_at)<=day&&cairoDate(g.end_at)>=day).map(g=>({...g,monitorId:m.id,camera:m.camera})));const unresolvedUnknown=Number(db.prepare('SELECT COUNT(*) n FROM unknown_crossings WHERE owner_id=? AND restaurant_id=? AND experiment_id IS NULL AND occurred_at>=? AND occurred_at<? AND resolved_at IS NULL').get((user.owner_id||user.id),r.id,interval.from,interval.to).n);const review=db.prepare('SELECT * FROM day_reviews WHERE owner_id=? AND restaurant_id=? AND business_date=?').get((user.owner_id||user.id),r.id,day)||null;const warnings=[];if(unresolvedUnknown)warnings.push('Unresolved unknown crossings exist; confirmed counts exclude them');if(!revision)warnings.push('POS data missing');if(!relevant.length)warnings.push('No monitoring coverage recorded for this business date');if(gaps.length)warnings.push('Monitoring gaps exist; observed counts may be incomplete');if(rows.some(r=>r.expectedOut===null))warnings.push('Some dishes have no POS expectation');return json(res,200,{businessDate:day,timeZone:'Africa/Cairo',interval,review,revision:revision?.revision||null,rows,coverage:{sessions:relevant,gaps,warnings,unresolvedUnknown,complete:false,note:'Heartbeats indicate processing availability, not recognition accuracy. Absence of events does not prove zero output.'}}),true;}
 if(p==='/api/monitor/start'&&method==='POST'){const r=restaurant(body.restaurantId,user),session=text(body.sessionId),camera=text(body.camera||'Mobile'),source=text(body.sourceId||camera,180);const previous=db.prepare('SELECT * FROM monitors WHERE user_id=? AND session_id=?').get((user.owner_id||user.id),session);if(previous){if(previous.restaurant_id!==r.id||previous.camera!==camera||previous.source_id&&previous.source_id!==source)fail(409,'Monitoring session already bound elsewhere');return json(res,200,{monitor:monitoring(r.id,user).find(m=>m.id===previous.id),duplicate:true}),true;}const now=new Date().toISOString();const old=db.prepare('SELECT * FROM monitors WHERE user_id=? AND restaurant_id=? AND COALESCE(source_id,camera)=? AND ended_at IS NULL').all((user.owner_id||user.id),r.id,source);db.exec('BEGIN');let id;try{for(const m of old){const gapStart=m.stalled_at||new Date(Math.min(Date.parse(now),Date.parse(m.last_heartbeat)+45000)).toISOString();if(gapStart<now)db.prepare('INSERT INTO monitor_gaps(monitor_id,start_at,end_at,cause) VALUES(?,?,?,?)').run(m.id,gapStart,now,m.stalled_at?'video_stalled':'unknown');db.prepare("UPDATE monitors SET ended_at=?,end_reason='source_recovered',stalled_at=NULL WHERE id=?").run(now,m.id);}id=db.prepare('INSERT INTO monitors(user_id,restaurant_id,session_id,camera,source_id,started_at,last_heartbeat) VALUES(?,?,?,?,?,?,?)').run((user.owner_id||user.id),r.id,session,camera,source,now,now).lastInsertRowid;db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}audit(user,'monitor.started',Number(id),{restaurantId:r.id,sourceId:source});return json(res,201,{monitor:monitoring(r.id,user).find(m=>m.id===Number(id))}),true;}
 match=p.match(/^\/api\/monitor\/(\d+)\/(heartbeat|end)$/);if(match&&method==='POST'){const m=monitor(match[1],user);if(m.ended_at&&match[2]==='heartbeat')fail(409,'Monitoring session ended');if(body.status!==undefined&&!['running','stalled'].includes(body.status))fail(400,'Invalid processing status');const now=new Date().toISOString();if(!m.ended_at){db.exec('BEGIN');try{if(!m.stalled_at&&Date.parse(now)-Date.parse(m.last_heartbeat)>45000)db.prepare('INSERT INTO monitor_gaps(monitor_id,start_at,end_at,cause) VALUES(?,?,?,?)').run(m.id,new Date(Date.parse(m.last_heartbeat)+45000).toISOString(),now,'unknown');if(m.stalled_at&&(match[2]==='end'||body.status!=='stalled'))db.prepare('INSERT INTO monitor_gaps(monitor_id,start_at,end_at,cause) VALUES(?,?,?,?)').run(m.id,m.stalled_at,now,'video_stalled');if(match[2]==='end')db.prepare('UPDATE monitors SET ended_at=?,end_reason=?,stalled_at=NULL WHERE id=?').run(now,text(body.reason||'user_stopped'),m.id);else db.prepare('UPDATE monitors SET last_heartbeat=?,stalled_at=? WHERE id=?').run(now,body.status==='stalled'?(m.stalled_at||now):null,m.id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}return json(res,200,{monitor:monitoring(m.restaurant_id,user).find(x=>x.id===m.id)}),true;}
 if(p==='/api/monitor'&&method==='GET'){const r=restaurant(url.searchParams.get('restaurantId'),user);return json(res,200,{monitors:monitoring(r.id,user),heartbeatIntervalSec:15,staleAfterSec:45}),true;}
 return false;
 }};
}
