import {objectBody,isoTime,pageQuery} from './validation.mjs';
export function initializeSources(db){db.exec(`CREATE TABLE IF NOT EXISTS sources(id INTEGER PRIMARY KEY,owner_id INTEGER NOT NULL,restaurant_id INTEGER NOT NULL,source_id TEXT NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,config TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(owner_id,source_id));CREATE TABLE IF NOT EXISTS source_producer_leases(id INTEGER PRIMARY KEY,source_id INTEGER NOT NULL,boot_id TEXT NOT NULL,valid_from TEXT NOT NULL,valid_until TEXT NOT NULL);CREATE INDEX IF NOT EXISTS source_lease_idx ON source_producer_leases(source_id,id);CREATE TABLE IF NOT EXISTS source_health(source_id INTEGER PRIMARY KEY,boot_id TEXT NOT NULL,sequence INTEGER NOT NULL,status TEXT NOT NULL,observed_at TEXT NOT NULL,received_at TEXT NOT NULL,metrics TEXT NOT NULL,error_code TEXT NOT NULL);CREATE TABLE IF NOT EXISTS source_gaps(id INTEGER PRIMARY KEY,source_id INTEGER NOT NULL,gap_id TEXT NOT NULL,start_at TEXT NOT NULL,end_at TEXT NOT NULL,cause TEXT NOT NULL,recoverable INTEGER NOT NULL,created_at TEXT NOT NULL,UNIQUE(source_id,gap_id));CREATE INDEX IF NOT EXISTS source_restaurant_idx ON sources(owner_id,restaurant_id,id);CREATE INDEX IF NOT EXISTS source_gap_time_idx ON source_gaps(source_id,start_at,end_at);`);}
export function createSources({db,access,fail,text}){
 const registered=(sourceId,rid,user)=>{if(sourceId===undefined||sourceId===null)return null;const key=text(sourceId,180);const row=db.prepare('SELECT * FROM sources WHERE owner_id=? AND restaurant_id=? AND source_id=?').get(access.tenantId(user),rid,key);if(!row)fail(404,'Source not found');if(!row.enabled)fail(409,'Source disabled');return row;};
 const owned=(id,user)=>{const row=db.prepare('SELECT * FROM sources WHERE id=? AND owner_id=?').get(Number(id),access.tenantId(user));if(!row)fail(404,'Source not found');access.restaurant(row.restaurant_id,user);return row;};
 const health=(id)=>{const h=db.prepare('SELECT * FROM source_health WHERE source_id=?').get(id);if(!h)return null;const ageSec=Math.max(0,(Date.now()-Date.parse(h.received_at))/1000);return{bootId:h.boot_id,sequence:h.sequence,status:h.status,observedAt:h.observed_at,receivedAt:h.received_at,metrics:JSON.parse(h.metrics),errorCode:h.error_code,ageSec,stale:ageSec>45,note:'Availability telemetry does not prove complete or accurate recognition.'};};
 const row=(s)=>({id:s.id,restaurantId:s.restaurant_id,sourceId:s.source_id,name:s.name,kind:s.kind,enabled:!!s.enabled,config:JSON.parse(s.config),createdAt:s.created_at,updatedAt:s.updated_at,health:health(s.id)});
 function config(value={},user){objectBody(value,'source config');const allowed=new Set(['roi','line','targetFps','maxObjects','modelProfileId']);if(Object.keys(value).some(k=>!allowed.has(k)))fail(400,'Source config accepts calibration only; URLs and credentials belong on the edge device');const output={targetFps:value.targetFps??5,maxObjects:value.maxObjects??4};if(value.modelProfileId!==undefined){if(!Number.isSafeInteger(value.modelProfileId)||!db.prepare('SELECT 1 FROM model_profiles WHERE id=? AND owner_id=?').get(value.modelProfileId,access.tenantId(user)))fail(400,'Invalid model profile');output.modelProfileId=value.modelProfileId;}if(typeof output.targetFps!=='number'||!Number.isFinite(output.targetFps)||output.targetFps<.1||output.targetFps>30||!Number.isInteger(output.maxObjects)||output.maxObjects<1||output.maxObjects>40)fail(400,'Invalid source sampling configuration');if(value.roi!==undefined){if(!Array.isArray(value.roi)||value.roi.length!==4||value.roi.some(n=>typeof n!=='number'||!Number.isFinite(n)||n<0||n>1)||value.roi[2]<=0||value.roi[3]<=0||value.roi[0]+value.roi[2]>1||value.roi[1]+value.roi[3]>1)fail(400,'Invalid normalized ROI');output.roi=value.roi;}if(value.line!==undefined){objectBody(value.line,'source line');const line=value.line;if(Object.keys(line).some(k=>!['orientation','position','direction'].includes(k))||!['horizontal','vertical'].includes(line.orientation)||typeof line.position!=='number'||!Number.isFinite(line.position)||line.position<=0||line.position>=1||!(line.orientation==='horizontal'?['up','down']:['left','right']).includes(line.direction))fail(400,'Invalid crossing line');output.line=line;}return output;}
 const enums=['none','decoder_unavailable','source_unreachable','auth_failed','inference_failed','storage_full','upload_failed','calibration_required'];
 const eventLease=(source,id,at,experimentId)=>{if(!source||experimentId!==null||!['rtsp','usb'].includes(source.kind))return null;if(!Number.isSafeInteger(id)||id<1)fail(409,'Live edge source requires an active producer lease');const lease=db.prepare('SELECT * FROM source_producer_leases WHERE id=? AND source_id=?').get(id,source.id);if(!lease||at<lease.valid_from||at>lease.valid_until)fail(409,'Event timestamp lies outside its producer lease');return lease.id;};
 return{registered,eventLease,async route({p,method,url,body,user,res,json}){
  if(p==='/api/sources'){
   const rid=method==='GET'?url.searchParams.get('restaurantId'):body.restaurantId,r=access.restaurant(rid,user);access.demand(user,method==='GET'?'monitor.read':'integrations.manage',r.id);
   if(method==='GET'){json(res,200,{sources:db.prepare('SELECT * FROM sources WHERE owner_id=? AND restaurant_id=? ORDER BY id').all(access.tenantId(user),r.id).map(row)});return true;}
   if(method==='POST'){if(Object.keys(body).some(k=>!['restaurantId','sourceId','name','kind','config'].includes(k)))fail(400,'Unsupported source field');const sourceId=text(body.sourceId,180);if(!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,179}$/.test(sourceId))fail(400,'Use a nonsecret source identifier');if(!['rtsp','usb','browser','file'].includes(body.kind))fail(400,'Invalid source kind');const c=config(body.config,user),name=text(body.name);if(db.prepare('SELECT 1 FROM sources WHERE owner_id=? AND source_id=?').get(access.tenantId(user),sourceId))fail(409,'Source identifier already exists');const now=new Date().toISOString(),id=db.prepare('INSERT INTO sources(owner_id,restaurant_id,source_id,name,kind,config,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(access.tenantId(user),r.id,sourceId,name,body.kind,JSON.stringify(c),now,now).lastInsertRowid;access.audit(user,'source.created',Number(id),{restaurantId:r.id,sourceId,kind:body.kind,config:c});json(res,201,{source:row(owned(id,user))});return true;}
  }
  const m=p.match(/^\/api\/sources\/(\d+)(?:\/(health|gaps|lease))?$/);if(!m)return false;const s=owned(m[1],user);
  if(!m[2]){access.demand(user,method==='GET'?'monitor.read':'integrations.manage',s.restaurant_id);if(method==='GET'){json(res,200,{source:row(s)});return true;}if(method==='POST'){if(Object.keys(body).some(k=>!['name','enabled','config'].includes(k)))fail(400,'Unsupported source field');if(body.enabled!==undefined&&typeof body.enabled!=='boolean')fail(400,'enabled must be boolean');const c=body.config===undefined?JSON.parse(s.config):config(body.config,user);db.prepare('UPDATE sources SET name=?,enabled=?,config=?,updated_at=? WHERE id=?').run(body.name===undefined?s.name:text(body.name),body.enabled===undefined?s.enabled:Number(body.enabled),JSON.stringify(c),new Date().toISOString(),s.id);access.audit(user,'source.updated',s.id,{restaurantId:s.restaurant_id,enabled:body.enabled,config:c});json(res,200,{source:row(owned(s.id,user))});return true;}}
  access.demand(user,method==='GET'?'monitor.read':'monitor.write',s.restaurant_id);
  if(m[2]==='lease'&&method==='POST'){
   if(!s.enabled)fail(409,'Source disabled');if(Object.keys(body).some(k=>!['bootId','ttlSec'].includes(k)))fail(400,'Unsupported lease field');const bootId=text(body.bootId),ttlSec=body.ttlSec??45;if(!Number.isSafeInteger(ttlSec)||ttlSec<30||ttlSec>60)fail(400,'Producer lease TTL must be30..60 seconds');const now=new Date().toISOString(),expiresAt=new Date(Date.now()+ttlSec*1000).toISOString(),previous=db.prepare('SELECT * FROM source_producer_leases WHERE source_id=? ORDER BY id DESC LIMIT 1').get(s.id);let leaseId;if(previous&&previous.valid_until>now){if(previous.boot_id!==bootId)fail(409,'Another producer owns this source lease');leaseId=previous.id;db.prepare('UPDATE source_producer_leases SET valid_until=? WHERE id=?').run(expiresAt,leaseId);}else{leaseId=Number(db.prepare('INSERT INTO source_producer_leases(source_id,boot_id,valid_from,valid_until) VALUES(?,?,?,?)').run(s.id,bootId,now,expiresAt).lastInsertRowid);access.audit(user,'source.lease-started',leaseId,{restaurantId:s.restaurant_id,sourceId:s.source_id,bootId,expiresAt});}json(res,200,{leaseId,expiresAt,serverTime:now});return true;
  }
  if(m[2]==='health'&&method==='GET'){json(res,200,{health:health(s.id)});return true;}
  if(m[2]==='health'&&method==='POST'){
   if(Object.keys(body).some(k=>!['status','bootId','sequence','observedAt','metrics','errorCode'].includes(k)))fail(400,'Unsupported health field; never send credentials or decoder messages');if(!['starting','running','stalled','offline','error'].includes(body.status)||!Number.isSafeInteger(body.sequence)||body.sequence<0)fail(400,'Invalid health state');const bootId=text(body.bootId),observedAt=isoTime(body.observedAt,'observation time'),errorCode=body.errorCode??'none';if(!enums.includes(errorCode))fail(400,'Invalid diagnostic code');const metrics=objectBody(body.metrics??{},'metrics'),allowed=['fps','frameAgeSec','queueDepth','oldestQueueAgeSec','freeDiskBytes','inferenceMs'];if(Object.keys(metrics).some(k=>!allowed.includes(k))||Object.entries(metrics).some(([k,v])=>typeof v!=='number'||!Number.isFinite(v)||v<0||['queueDepth','freeDiskBytes'].includes(k)&&!Number.isSafeInteger(v)))fail(400,'Invalid health metrics');const previous=db.prepare('SELECT * FROM source_health WHERE source_id=?').get(s.id);if(previous&&previous.boot_id===bootId&&body.sequence<=previous.sequence){if(body.sequence===previous.sequence&&previous.status===body.status&&previous.observed_at===observedAt&&previous.metrics===JSON.stringify(metrics)&&previous.error_code===errorCode){json(res,200,{health:health(s.id),duplicate:true,serverReceivedAt:previous.received_at});return true;}fail(409,'Health sequence is stale or changed');}const now=new Date().toISOString();db.prepare('INSERT INTO source_health VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(source_id) DO UPDATE SET boot_id=excluded.boot_id,sequence=excluded.sequence,status=excluded.status,observed_at=excluded.observed_at,received_at=excluded.received_at,metrics=excluded.metrics,error_code=excluded.error_code').run(s.id,bootId,body.sequence,body.status,observedAt,now,JSON.stringify(metrics),errorCode);json(res,200,{health:health(s.id),serverReceivedAt:now});return true;
  }
  if(m[2]==='gaps'){
   if(method==='GET'){const{limit,beforeId}=pageQuery(url);const records=db.prepare('SELECT * FROM source_gaps WHERE source_id=? AND (? IS NULL OR id<?) ORDER BY id DESC LIMIT ?').all(s.id,beforeId,beforeId,limit+1),hasMore=records.length>limit;if(hasMore)records.pop();json(res,200,{records,hasMore,nextBeforeId:hasMore?records.at(-1).id:null});return true;}
   if(method==='POST'){if(Object.keys(body).some(k=>!['gapId','startAt','endAt','cause','recoverable'].includes(k)))fail(400,'Unsupported gap field');const gapId=text(body.gapId),startAt=isoTime(body.startAt,'gap start'),endAt=isoTime(body.endAt,'gap end');if(startAt>=endAt||!['power_loss','source_unreachable','video_stalled','upload_failed','inference_failed','process_restart','unknown'].includes(body.cause)||typeof body.recoverable!=='boolean')fail(400,'Invalid source gap');const previous=db.prepare('SELECT * FROM source_gaps WHERE source_id=? AND gap_id=?').get(s.id,gapId);if(previous){if(previous.start_at!==startAt||previous.end_at!==endAt||previous.cause!==body.cause||previous.recoverable!==Number(body.recoverable))fail(409,'Gap identifier already has different data');json(res,200,{id:previous.id,duplicate:true});return true;}const id=db.prepare('INSERT INTO source_gaps(source_id,gap_id,start_at,end_at,cause,recoverable,created_at) VALUES(?,?,?,?,?,?,?)').run(s.id,gapId,startAt,endAt,body.cause,Number(body.recoverable),new Date().toISOString()).lastInsertRowid;access.audit(user,'source.gap',Number(id),{restaurantId:s.restaurant_id,sourceId:s.source_id,cause:body.cause,startAt,endAt,recoverable:body.recoverable});json(res,201,{id,duplicate:false});return true;}
  }
  return false;
 }};
}
